source 'http://rubygems.org'

gem 'rails', '3.1.12'
gem 'rake'
gem 'rdoc'
gem 'rdoc-data'
gem 'mysql2', '~> 0.3.20'

# rails 2.3.x -> 3.0.x
#   form_for / f.error_messages
gem 'dynamic_form'

group :assets do
  gem 'sass-rails',   '~> 3.1.7'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier',     '>= 1.0.3'
end

gem 'jquery-rails'
gem 'therubyracer'
