source 'http://rubygems.org'

gem 'rails', '4.0.13'
gem 'rake'
gem 'rdoc'
gem 'rdoc-data'
gem 'mysql2', '~> 0.3.20'

# rails 2.3.x -> 3.0.x
#   form_for / f.error_messages
gem 'dynamic_form'

gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

gem 'jquery-rails'
gem 'therubyracer'
gem 'activerecord-session_store'
